version: '3.6'
services:
  squid:
    image: 'hackseal/squid:latest'
    restart: always
    hostname: 'docker-squid'
    container_name: 'docker-squid'
    privileged: true
    ports:
      - '3128:3128'
    volumes:
      - ./config/:/etc/squid
      - ./cache:/var/cache/squid
      - ./logs:/var/log/squid/
      - /etc/localtime:/etc/localtime
